# -----
# This work is licensed under the Creative Commons Attribution 3.0 Unported License. To view a copy  # of this license, visit http://creativecommons.org/licenses/by/3.0/.
# -----

# -----
# @author      Daniel Zamorano <daniel.zamorano.m@gmail.com>
# @version     0.1
# @since       2013-03-01
# -----


deploy-path:            /Users/dz/Dropbox/public/
deploy-folder-name:     site
release-main-folder:    ../site
version-file:           ../version.txt